SHOW DATABASES;
USE mydata;
CREATE TABLE myproduct(
	MYKEY INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRODUCTID TEXT,
    TITLE TEXT, 
    ORI_PRICE INT,
    DISCOUNT_PRICE INT,
    DISCOUNT_PERCENT INT,
    DELEVERY TEXT,
    PRIMARY KEY(MYKEY)
);
SHOW TABLES;
DESC myproduct;
CREATE TABLE customer_db(
	no INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name CHAR(20) NOT NULL,
    age TINYINT,
    phone VARCHAR(20),
    email VARCHAR(30) NOT NULL,
    address VARCHAR(50),
    PRIMARY KEY(no)
);
DROP TABLE customer_db;
DESC customer_db;